static_transforms:
  - parent_frame: base_link
    child_frame: camera_link
    translation_xyz_m: [0.0, 0.0, 0.0]
    rotation_rpy_rad: [0.0, 0.0, 0.0]
  - parent_frame: base_link
    child_frame: imu_link
    translation_xyz_m: [0.0, 0.0, 0.0]
    rotation_rpy_rad: [0.0, 0.0, 0.0]
